# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-12-07 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('status', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('disabled_at', models.DateField()),
                ('status', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity_api.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity_api.Property'),
        ),
    ]
