# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-12-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='schedule',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='disabled_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
