# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-12-07 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0002_auto_20211207_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='disabled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
