# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-12-07 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0003_auto_20211207_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='answer',
            field=jsonfield.fields.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
